# This file was generated by GoReleaser. DO NOT EDIT.
cask "worktrack" do
  version "1.0.1"

  on_macos do
    on_arm do
      sha256 "c4e3f3582307d3e994889fbb5e6e2c978f536dd645d50c80a0ed054aeb17183c"
      url "https://github.com/bastigamedc/tracker/releases/download/v#{version}/worktrack_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7677b32f151b6c7d4a4e6b0936b1a573d8b23026f7f4de7f2c4c7021b9fcdbdd"
      url "https://github.com/bastigamedc/tracker/releases/download/v#{version}/worktrack_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "abfc77ee31763e38d28071d75415271d4b113975fb65900d072d5f432f4c04b1"
      url "https://github.com/bastigamedc/tracker/releases/download/v#{version}/worktrack_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "848bb91ca261beae361182463bebc620db0a5996041257aa592bdd1da7cde580"
      url "https://github.com/bastigamedc/tracker/releases/download/v#{version}/worktrack_#{version}_linux_amd64.tar.gz"
    end
  end

  name "worktrack"
  desc "Zeiterfassung für mehrere Firmen - Terminal TUI"
  homepage "https://github.com/bastigamedc/tracker"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "worktrack"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/worktrack"]
    end
  end

  # No zap stanza required
end
